
- name: Set hostname
  hostname:
    name: "{{ hostname }}"

# - name: Change password
#   user:
#     name: pi
#     password: "{{ password }}"
#     state: present

- name: Create locale
  locale_gen:
    name: de_DE.UTF-8
    state: present

# TODO: set locale

# - name: apt-update
  # shell: apt-get update

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
    update_cache: yes



- name: Ensure .ssh folder
  file:
    path: /home/pi/.ssh
    state: directory
    owner: pi
    group: pi
    mode: 0700

- name: Deploy ssh public keys for login
  template:
    src: authorized_keys.j2
    dest:  /home/pi/.ssh/authorized_keys
    owner: pi
    group: pi
    mode:  0644

- name: Install dependencies
  apt:
    name:
      - python3
      - git
      - python3-dev
      - python3-venv
    state: present


- name: purge unneeded packages
  apt:
    name:
      - chromium-browser
      - unclutter
      - xdotool
      - wolfram-engine
      - scratch
      - nuscratch
      - sonic-pi
      - idle3
      - smartsim
      - penguinspuzzle
      - java-common
      - minecraft-pi
      - python-minecraftpi
      - python3-minecraftpi
      - dphys-swapfile # removing swap, improves sd life but kills
    state: absent
    autoremove: yes
